yaml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,15 +20,13 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Zorg ervoor dat je private key in GitHub secrets staat
 
-      # Stap 3: Voeg de SSH-host toe aan known_hosts met gedetailleerde foutlogging en netwerkcontrole
+      # Stap 3: Voeg de SSH-host toe aan known_hosts
       - name: Add SSH host to known_hosts
         run: |
           echo "Creating .ssh directory"
           mkdir -p $HOME/.ssh
-          echo "Pinging host to check connectivity"
-          ping -c 4 89.117.228.91 || { echo "Ping failed"; exit 1; }
           echo "Adding host key"
-          ssh-keyscan -t rsa -v 89.117.228.91 >> $HOME/.ssh/known_hosts || { echo "Failed to run ssh-keyscan"; exit 1; }
+          ssh-keyscan -t rsa 89.117.228.91 >> $HOME/.ssh/known_hosts || { echo "Failed to run ssh-keyscan"; exit 1; }
           echo "Host key added successfully"
           cat $HOME/.ssh/known_hosts  # Bekijk het bestand om te controleren
           chmod 644 $HOME/.ssh/known_hosts || { echo "Failed to change permissions"; exit 1; }
@@ -36,18 +34,14 @@ jobs:
           ls -al $HOME/.ssh  # Controleer de inhoud van de .ssh directory
           echo "Done with SSH setup"
 
-      # Stap 4: Voer de deploy naar Hostinger uit via SSH
+      # Stap 4: Test SSH-verbinding
       - name: Test SSH connection
         run: |
           ssh -o StrictHostKeyChecking=no -p 65002 u503411290@89.117.228.91 "echo 'SSH connection successful'"
           echo "SSH connection test passed"
 
-      # Stap 5: Voer de deploy naar Hostinger uit via SSH
-      - name: Deploy to Hostinger
+      # Stap 5: Voer een simpel commando uit op de server via SSH om te testen
+      - name: Run command on Hostinger
         run: |
-          echo "Starting SSH deploy"
-          ssh -o StrictHostKeyChecking=no -p 65002 u503411290@89.117.228.91 << 'EOF'
-            cd /home/u503411290/domains/janvanerkel.nl/public_html/admin
-            git pull origin main  # Trek de laatste wijzigingen op van de 'main' branch
-          EOF
-          echo "Deploy complete"
+          ssh -o StrictHostKeyChecking=no -p 65002 u503411290@89.117.228.91 "hostname && date"
+          echo "Command execution on server complete"
